036_MoviesMvcWissen/Models/Demos/Templates/PersonModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _036_MoviesMvcWissen.Models.Demos.Templates
{
    public class PersonModel
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public bool GraduatedFromUniversity { get; set; }
        public string IdentityNo { get; set; }
        public DateTime? BirthDate { get; set; }

    }
}

036_MoviesMvcWissen/Controllers/DemosController.cs
using _036_MoviesMvcWissen.Models.Demos.Templates;
using _036_MoviesMvcWissen.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace _036_MoviesMvcWissen.Controllers
{
    #region Razor Demos
    public static class NameUtil
    {
        public static string GetName()
        {
            return "Name: Çağıl Alsaç";
        }
    }
    #endregion

    public class DemosController : Controller
    {
        #region Razor Demos
        public ActionResult Razor1() // kodlar için view'a gidilmelidir.
        {
            return View();
        }

        public ActionResult Razor2() // kodlar için view'a gidilmelidir.
        {
            return View();
        }
        #endregion

        #region Route Values

        public string FromRoute(int id)
        {
            return id.ToString();
        }
        // 9?name=çağil&lastname=alsaç
        #endregion

        #region Query String

        //public string FromQueryString(string name, string surname)
        //{
        //    return name + " " + surname;
        //}

        public string FromQueryString()
        {
            var name = Request.QueryString["name"];
            var surname = Request.QueryString["surname"];
            return name + " " + surname;
        }


        #endregion

        #region Templates
        public ActionResult GetPeople()
        {
            List<PersonModel> people;
            if (Session["people"] == null)
            {
                people = new List<PersonModel>()
                {
                    new PersonModel()
                    {
                        Id = 1,
                        FullName ="Çağıl Alsaç",
                        IdentityNo = "123456",
                        GraduatedFromUniversity = true,
                        BirthDate = DateTime.Parse("19.06.1980")
                    },
                    new PersonModel()
                    {
                        Id = 2,
                        FullName ="Leo Alsaç",
                        IdentityNo = "654321",
                        GraduatedFromUniversity = false,
                        BirthDate = DateTime.Parse("25.05.2015")
                    }
                };
                Session["people"] = people;
            }
            else
            {
                people = Session["people"] as List<PersonModel>;
            }
            return View(people);
        }

        public ActionResult GetPersonDetails(int id)
        {
            List<PersonModel> people = Session["people"] as List<PersonModel>;
            PersonModel person = people.SingleOrDefault(e => e.Id == id);
            return View(person);
        }

        public ActionResult AddPerson()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPerson(PersonModel personModel)
        {
            List<PersonModel> people = Session["people"] as List<PersonModel>;
            personModel.Id = people.Max(e => e.Id) + 1;
            people.Add(personModel);
            Session["people"] = people;
            return RedirectToAction("GetPeople");
        }

        #endregion

        #region HandleError Action Filter
        [HandleError]
        public ActionResult DivideByZero()
        {
            var no1 = 14;
            var no2 = 0;
            var result = no1 / no2;
            ViewBag.Result = result;
            return View();
        }


        #endregion

        #region AJAX
        public ActionResult GetPeopleAjax()
        {
            List<PersonModel> people;
            if (Session["people"] == null)
            {
                people = new List<PersonModel>()
                {
                    new PersonModel()
                    {
                        Id = 1,
                        FullName ="Çağıl Alsaç",
                        IdentityNo = "123456",
                        GraduatedFromUniversity = true,
                        BirthDate = DateTime.Parse("19.06.1980")
                    },
                    new PersonModel()
                    {
                        Id = 2,
                        FullName ="Leo Alsaç",
                        IdentityNo = "654321",
                        GraduatedFromUniversity = false,
                        BirthDate = DateTime.Parse("25.05.2015")
                    },
                     new PersonModel()
                    {
                        Id = 3,
                        FullName ="Ugur Karasar",
                        IdentityNo = "333333",
                        GraduatedFromUniversity = true,
                        BirthDate = DateTime.Parse("14.01.1994")
                    },
                      new PersonModel()
                    {
                        Id = 4,
                        FullName ="Deneme Test",
                        IdentityNo = "000000",
                        GraduatedFromUniversity = false,
                        BirthDate = DateTime.Parse("17.02.2020")
                    }
                };
                Session["people"] = people;
            }
            else
            {
                people = Session["people"] as List<PersonModel>;
            }
            DemosGetPeopleAjaxViewModel model = new DemosGetPeopleAjaxViewModel()// 14.02.2020 - 20:48
            {
                PeopleModel = people,
                PersonModel = new PersonModel()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult AddPersonAjax(PersonModel personModel)
        {
            //Thread.Sleep(3000);
            List<PersonModel> people = Session["people"] as List<PersonModel>;
            personModel.Id = people.Max(e => e.Id) + 1;
            people.Add(personModel);
            Session["people"] = people;
            //return RedirectToAction("GetPeopleAjax"); // Ajax sadece belli bir yeri güncelleme redirect ile olmuyor

            //var model = new DemosGetPeopleAjaxViewModel()// 1.  yol bütün view i döndüğü için bu da ynalış
            //{
            //    PeopleModel = people
            //};
            //return View("GetPeopleAjax", people);

            return PartialView("_PeopleList",people);

        }
        public ActionResult DeletePersonAjax(int? id)
        {
            //Thread.Sleep(3000);
            List<PersonModel> people = Session["people"] as List<PersonModel>;
            //PersonModel person = people.SingleOrDefault(e => e.Id == id);
            var person = people.FirstOrDefault(e => e.Id == id);
            people.Remove(person);
            Session["people"] = people;
            return PartialView("_PeopleList", people);
            
        }
        // GetPeopleAjax kısmı buraya kadar //Ajax yapma yöntemi ilk mvc yukarıdaki

        //DemosPeople.html // 2. cisi ayrı html de
        public ActionResult GetPeopleJson()
        {
            if(Request.IsAjaxRequest())
            {
                var people = new List<PersonModel>()
            {
                 new PersonModel()
                    {
                        Id = 1,
                        FullName ="Çağıl Alsaç",
                        IdentityNo = "123456",
                        GraduatedFromUniversity = true,
                        BirthDate = DateTime.Parse("19.06.1980")
                    },
                    new PersonModel()
                    {
                        Id = 2,
                        FullName ="Leo Alsaç",
                        IdentityNo = "654321",
                        GraduatedFromUniversity = false,
                        BirthDate = DateTime.Parse("25.05.2015")
                    },
                     new PersonModel()
                    {
                        Id = 3,
                        FullName ="Ugur Karasar",
                        IdentityNo = "333333",
                        GraduatedFromUniversity = true,
                        BirthDate = DateTime.Parse("14.01.1994")
                    },
                      new PersonModel()
                    {
                        Id = 4,
                        FullName ="Deneme Test",
                        IdentityNo = "000000",
                        GraduatedFromUniversity = false,
                        BirthDate = DateTime.Parse("17.02.2020")
                    }
            };

                var model = people.Select(e => new PersonModelClientModel()
                {
                    Id = e.Id,
                    FullName = e.FullName,
                    IdentityNo = e.IdentityNo,
                    GraduatedFromUniversity = e.GraduatedFromUniversity,
                    BirthDate = e.BirthDate.HasValue ? e.BirthDate.Value.ToShortDateString() : ""
                });

                return Json(model, JsonRequestBehavior.AllowGet);
            }

            return new EmptyResult();

        }

        public RedirectResult GetPeopleHtml()
        {
            return RedirectPermanent("~/DemosPeople.html");
        }

        #endregion

        #region Route Attribute
        //[Route("demos/addnumbers/{no1}/{no2}")]
        [Route("addtwonumbers/{no1}/{no2}")]
        public ActionResult AddNumbers(int no1, int no2)
        {
            return Content((no1 + no2).ToString());
        }



        #endregion


    }
}

036_MoviesMvcWissen/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?


<div>
    @Html.TextBoxFor(e => e, new { @class = "form-control-sm date-picker" })
    @*d try it at home*@
    @*<span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>*@
</div>

<script>
        $(function () {
            $('.date-picker').datepicker({
                format: "dd.mm.yyyy"

            });
        });
</script>

@*<div class='input-group date' id='datetimepicker1'>
        <input type='text' class="form-control" />
       <span class="input-group-addon">
           <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>*@

036_MoviesMvcWissen/Views/Shared/EditorTemplates/PersonModel.cshtml
@model _036_MoviesMvcWissen.Models.Demos.Templates.PersonModel

@{
    ViewBag.Title = "AddPerson";
}

<h2>AddPerson (From Our Editor Template)</h2>
                                                    @*session temizleme autocomplete = "off"*@
@using (Html.BeginForm("AddPerson", "Demos", FormMethod.Post, new { autocomplete = "off"})) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PersonModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GraduatedFromUniversity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GraduatedFromUniversity)
                    @Html.ValidationMessageFor(model => model.GraduatedFromUniversity, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdentityNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdentityNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdentityNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, "Date") @* şablonu belirttik*@
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}