036_MoviesMvcWissen/Controllers/MoviesController.cs
using _036_MoviesMvcWissen.Contexts;
using _036_MoviesMvcWissen.Entities;
using _036_MoviesMvcWissen.Models;
using _036_MoviesMvcWissen.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace _036_MoviesMvcWissen.Controllers
{
    public class MoviesController : Controller
    {
        MoviesContext db = new MoviesContext();

        // GET: Movies
        //public ViewResult Index() // 1
        public ViewResult Index(MoviesIndexViewModel moviesIndexViewModel) // 2
        {
            // 1
            ////var model = db.Movies.ToList();
            //var model = GetList();
            ////ViewBag.count = model.Count;
            //ViewData["count"] = model.Count;
            //return View(model);

            // 2
            var years = new List<SelectListItem>();
            //years.Add(new SelectListItem()
            //{
            //    Value = "",
            //    Text = "-- All --"
            //});
            for (int i = DateTime.Now.Year; i >= 2000; i--)
            {
                years.Add(new SelectListItem()
                {
                    Value = i.ToString(),
                    Text = i.ToString()
                });
            }
            if (moviesIndexViewModel == null)
            {
                moviesIndexViewModel = new MoviesIndexViewModel();
            }
            if (String.IsNullOrWhiteSpace(moviesIndexViewModel.YearId))
            {
                moviesIndexViewModel.Movies = GetList();
            }
            else
            {
                moviesIndexViewModel.Movies = GetList().Where(e => e.ProductionYear == moviesIndexViewModel.YearId).ToList();
            }
            moviesIndexViewModel.Years = new SelectList(years, "Value", "Text", moviesIndexViewModel.YearId);
            return View(moviesIndexViewModel);
        }


        [OutputCache(Duration = 60, Location = OutputCacheLocation.ServerAndClient, NoStore = true, VaryByParam = "*")] // VaryByParam = "Name;Min;Max" , VaryByParam = "none"
        public ActionResult List(MoviesIndexViewModel moviesIndexViewModel)// son yaptığımız 16:00-17:00 (Hüseyin)
        {
            if (moviesIndexViewModel == null)
                moviesIndexViewModel = new MoviesIndexViewModel();

            var movies = db.Movies.AsQueryable();

            if (!string.IsNullOrWhiteSpace(moviesIndexViewModel.Name))
            {
                movies = movies.Where(e => e.Name.Contains(moviesIndexViewModel.Name));
            }
            if(!string.IsNullOrWhiteSpace(moviesIndexViewModel.YearId))
            {
                movies = movies.Where(e => e.ProductionYear == moviesIndexViewModel.YearId);
            }

            //if(!string.IsNullOrWhiteSpace(moviesIndexViewModel.Min) && !string.IsNullOrWhiteSpace(moviesIndexViewModel.Max))
            //{
            //    double minValue = 0;
            //    double maxValue = Convert.ToDouble(moviesIndexViewModel.Max);
            //    if (double.TryParse(moviesIndexViewModel.Min,out minValue))
            //    {
            //        movies = movies.Where(e => e.BoxOfficeReturn >= minValue & e.BoxOfficeReturn <= maxValue);
            //    }
            //}
            if (!string.IsNullOrWhiteSpace(moviesIndexViewModel.Min))
            {
                double minValue = 0;
                if (double.TryParse(moviesIndexViewModel.Min, out minValue))
                {
                    movies = movies.Where(e => e.BoxOfficeReturn <= minValue);
                }
            }
            if (!string.IsNullOrWhiteSpace(moviesIndexViewModel.Max))
            {
                double maxValue = 0;
                if (double.TryParse(moviesIndexViewModel.Max, out maxValue))
                {
                    movies = movies.Where(e => e.BoxOfficeReturn <= maxValue);
                }
            }


            moviesIndexViewModel.Movies = movies.ToList();


            var years = new List<SelectListItem>();
            for (int i = DateTime.Now.Year; i >= 1960; i--)
            {
                years.Add(new SelectListItem()
                {
                    Value = i.ToString(),
                    Text = i.ToString()
                });
            }

            moviesIndexViewModel.Years = new SelectList(years, "Value", "Text", moviesIndexViewModel.YearId);
            return View(moviesIndexViewModel);
        }


        [NonAction]
        public List<Movie> GetList(bool removeSession = true)
        {
            List<Movie> entities;
            if (removeSession)
                Session.Remove("movies");
            if (Session["movies"] == null || removeSession)
            {
                entities = db.Movies.ToList();
                Session["movies"] = entities;
            }
            else
            {
                entities = Session["movies"] as List<Movie>;
            }
            return entities;
        }

        public ActionResult GetMoviesFromSession()
        {
            var model = GetList(false);
            ViewBag.count = model.Count;
            return View("Index", model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.Message = "Please enter movie information...";
            var directors = db.Directors.ToList().Select(e => new SelectListItem()
            {
                Value = e.Id.ToString(),
                Text = e.Name + " " + e.Surname
            }).ToList();
            ViewData["directors"] = new MultiSelectList(directors, "Value", "Text");
            return View();
        }

        private string CreateFilePath(string Name, HttpPostedFileBase Image)
        {
            string filePath = "";
            if (Image != null && Image.ContentLength > 0)//s // dosya işlemi(Image) 
            {
                var fileName = DateTime.Now.Year + DateTime.Now.Month.ToString().PadLeft(2, '0') + DateTime.Now.Day.ToString().PadLeft(2, '0') + DateTime.Now.Hour.ToString().PadLeft(2, '0') + DateTime.Now.Minute.ToString().PadLeft(2, '0') + DateTime.Now.Second.ToString().PadLeft(2, '0') + DateTime.Now.Millisecond.ToString().PadLeft(3, '0') + "_" + Name.Replace(" ", "") + Path.GetExtension(Image.FileName);
                // filepath ı oluşturma
                if (Path.GetExtension(fileName).ToLower().Equals(".jpg") || Path.GetExtension(fileName).ToLower().Equals(".jpeg") || Path.GetExtension(fileName).ToLower().Equals(".png") || Path.GetExtension(fileName).ToLower().Equals(".bmp"))
                {
                    var filesFolder = Server.MapPath("~/" + ConfigurationManager.AppSettings["FilesFolder"]);
                    if (!Directory.Exists(filesFolder))
                        Directory.CreateDirectory(filesFolder);
                    var moviesFolder = filesFolder + @"\Movies";
                    if (!Directory.Exists(moviesFolder))
                        Directory.CreateDirectory(moviesFolder);
                    filePath = ConfigurationManager.AppSettings["FilesFolder"] + "/Movies/" + fileName; // virtual path olmalı veritabanına kaydettiğimiz path
                    //filePath = Path.Combine(Server.MapPath("~/Files/Movies"), fileName);//fiziksel path sıkinti çıkarir başka pcde
                }
            }
            return filePath;
        }

        [HttpPost]
        public RedirectToRouteResult Add(string Name, int ProductionYear, string BoxOfficeReturn, List<int> Directors, HttpPostedFileBase Image)
        {
            string filePath = CreateFilePath(Name,Image); // path oluşturmayı yukarıda methoda taşıdık
            
            var entity = new Movie()
            {
                Id = 0,
                Name = Name,
                ProductionYear = ProductionYear.ToString(),
                BoxOfficeReturn = Convert.ToDouble(BoxOfficeReturn.Replace(",", "."), CultureInfo.InvariantCulture),
                FilePath = filePath
            };
            entity.MovieDirectors = Directors.Select(e => new MovieDirector()
            {
                MovieId = entity.Id,
                DirectorId = e
            }).ToList();
            db.Movies.Add(entity);
            db.SaveChanges();
            if(filePath != null )// dosya işlemi(Image)
            {
                Image.SaveAs(Server.MapPath("~/" + filePath));// dosya ile ilgili istediğimiz işlemleri yapariz
            }
            Debug.WriteLine("Added Entity Id: " + entity.Id);
            TempData["Info"] = "Record successfully added to database.";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Id is required!");
            var model = db.Movies.Find(id.Value);
            List<SelectListItem> years = new List<SelectListItem>();
            SelectListItem year;
            for (int i = DateTime.Now.Year; i >= 2000; i--)
            {
                year = new SelectListItem() { Value = i.ToString(), Text = i.ToString() };
                years.Add(year);
            }
            ViewBag.Years = new SelectList(years, "Value", "Text", model.ProductionYear);
            var directors = db.Directors.Select(e => new DirectorModel()
            {
                Id = e.Id,
                FullName = e.Name + " " + e.Surname
            }).ToList();
            var directorIds = model.MovieDirectors.Select(e => e.DirectorId).ToList();
            ViewBag.directors = new MultiSelectList(directors, "Id", "FullName", directorIds);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, Name, ProductionYear")]Movie movie, string BoxOfficeReturn, List<int> directorIds, HttpPostedFileBase Image)

036_MoviesMvcWissen/Controllers/ReportsController.cs
using _036_MoviesMvcWissen.Contexts;
using _036_MoviesMvcWissen.Models;
using _036_MoviesMvcWissen.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.SqlServer;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _036_MoviesMvcWissen.Controllers
{
    public class ReportsController : Controller
    {
        MoviesContext db = new MoviesContext();  // MovieReportModel and ReportsController
        public ActionResult Movies(ReportsMoviesViewModel reportsMoviesViewModel)
        {
            GetModel(reportsMoviesViewModel);
            return View(reportsMoviesViewModel);
        }
        public ActionResult MoviesAjax(ReportsMoviesViewModel reportsMoviesViewModel)
        {
            GetModel(reportsMoviesViewModel);
            return PartialView("_Movies", reportsMoviesViewModel);
            
        }
        private void GetModel(ReportsMoviesViewModel reportsMoviesViewModel)
        {
            var movieQuery = db.Movies.AsQueryable();
            var directoryQuery = db.Directors.AsQueryable();
            var movieDirectoryQuery = db.MovieDirectors.AsQueryable();
            var reviewQuery = db.Reviews.AsQueryable();

            // inner join ile yapılışı
            //var query = from m in movieQuery // Paging, vahiyooooooo
            //            join md in movieDirectoryQuery
            //            on m.Id equals md.MovieId
            //            join d in directoryQuery
            //            on md.DirectorId equals d.Id
            //            join r in reviewQuery
            //            on m.Id equals r.MovieId
            //            select new MovieReportModel()
            //            {
            //                MovieId = m.Id,
            //                MovieName = m.Name,
            //                MovieProductionYear = m.ProductionYear,
            //                MovieBoxOfficeReturn = m.BoxOfficeReturn.HasValue ? m.BoxOfficeReturn.Value.ToString("C", new CultureInfo("tr")) : "",
            //                DirectorFullName = d.Name + d.Surname,
            //                DirectorRetired = d.Retired ? "Yes" : "No",
            //                ReviewContent = r.Content,
            //                ReviewRating = r.Rating,
            //                ReviewReviewer = r.Reviewer
            //            };

            // left outer join // ;_;

            var query = from m in movieQuery
                        join md in movieDirectoryQuery
                        on m.Id equals md.MovieId into movie_moviedirector
                        from sub_movie_moviedirector in movie_moviedirector.DefaultIfEmpty()

                        join d in directoryQuery
                        on sub_movie_moviedirector.DirectorId equals d.Id into moviedirector_director
                        from sub_moviedirector_director in moviedirector_director.DefaultIfEmpty()

                        join r in reviewQuery
                        on m.Id equals r.MovieId into movie_review
                        from sub_movie_review in movie_review.DefaultIfEmpty()

                        select new MovieReportModel()
                        {
                            MovieId = m.Id,
                            MovieName = m.Name,
                            MovieProductionYear = m.ProductionYear,
                            _MovieBoxOfficeReturn = m.BoxOfficeReturn,
                            DirectorFullName = sub_moviedirector_director.Name + " " + sub_moviedirector_director.Surname,
                            _DirectorRetired = sub_moviedirector_director.Retired,
                            ReviewContent = sub_movie_review.Content,
                            ReviewRating = sub_movie_review.Rating,
                            ReviewReviewer = sub_movie_review.Reviewer
                        };

            var recordCount = query.Count();
            reportsMoviesViewModel.RecordsPerPageCount = Convert.ToInt32(ConfigurationManager.AppSettings["ReportsMoviesRecordsPerPage"]);

            query = query.OrderBy(E => E.MovieName);
            query = query.Skip((reportsMoviesViewModel.PageNumber - 1) * reportsMoviesViewModel.RecordsPerPageCount).Take(reportsMoviesViewModel.RecordsPerPageCount);

            var list = query.ToList().Select(e => new MovieReportModel()
            {
                MovieId = e.MovieId,
                MovieName = e.MovieName,
                MovieProductionYear = e.MovieProductionYear,
                MovieBoxOfficeReturn = e._MovieBoxOfficeReturn.HasValue ? e._MovieBoxOfficeReturn.Value.ToString("C", new CultureInfo("tr")) : "",
                DirectorFullName = e.DirectorFullName,
                DirectorRetired = e._DirectorRetired ? "Yes" : "No",
                ReviewContent = e.ReviewContent,
                ReviewRating = e.ReviewRating,
                ReviewReviewer = e.ReviewReviewer
            }).ToList();

            reportsMoviesViewModel.MovieReports = list;
            reportsMoviesViewModel.RecordCount = recordCount;
            //kaç sayfa olduğunu hesapladık altta, recordcount'ı sayfada olmasını istediğimiz count sayısına(recordsperpagecount) a böldük
            int numberOfPages = Convert.ToInt32(Math.Ceiling((decimal)reportsMoviesViewModel.RecordCount / (decimal)reportsMoviesViewModel.RecordsPerPageCount));
            List<SelectListItem> pageList = new List<SelectListItem>();
            SelectListItem pageItem;

            for (int i = 1; i <= numberOfPages; i++)
            {
                pageItem = new SelectListItem()
                {
                    Value = i.ToString(),
                    Text = i.ToString()
                };
                pageList.Add(pageItem);
            }
            reportsMoviesViewModel.PageNumbers = new SelectList(pageList, "Value", "Text", reportsMoviesViewModel.PageNumber);
            //return reportsMoviesViewModel;
        }


    }

}

036_MoviesMvcWissen/Views/Movies/Add.cshtml
@*ADD SAYFASII*@
@{
    ViewBag.Title = "Add Movie";
    var directors = (MultiSelectList)ViewData["directors"];
}

<h2>@ViewBag.Title</h2>

<p style="color: #ffd800;">
    @ViewBag.Message
</p>

<form action="~/Movies/Add" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="tbName">Name</label>&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="text" class="form-control-sm" id="tbName" name="Name" />
    </div>
    <div class="form-group">
        <label for="ddlProductionYear">Production Year  </label>&nbsp;&nbsp;
        <select id="ddlProductionYear" name="ProductionYear" class="form-control-sm">
            @*<option value="2020" selected>2020</option>
                <option value="2019">2019</option>*@
            @for (int i = DateTime.Now.Year; i >= 1990; i--)
            {
                <option value="@i">@i</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="tbBoxOfficeReturn">Box Office Return </label>
        <input type="text" class="form-control-sm" id="tbBoxOfficeReturn" name="BoxOfficeReturn" />
    </div>

    <div class="form-group">
        <label for="ddlDirectos">Directors</label>
        <select id="ddlDirectos" class="form-control" name="Directors" multiple>
            @foreach(var director in directors)
            {
                <option value="@director.Value">@director.Text</option>
            }
        </select>
        @*@Html.ListBox()*@
    </div>

    <div class="form-group">
        <label for="fuImage">Image</label>
        <br />
        <input type="file" name="Image" accept="image/*" id="fuImage" />
    </div>


    <button type="submit" class="btn btn-primary">Save</button>
    &nbsp;
    <button type="reset" class="btn btn-info">Clear</button>
</form>

036_MoviesMvcWissen/Views/Movies/Delete.cshtml
@model Movie
@{
    /**/

    ViewBag.Title = "Delete Movie";
}

<h2>@ViewBag.Title</h2>

@*Bunun yerine partial view kullanyoruz
<div class="row">
    <div class="col-md-2">
        <b>@Html.DisplayNameFor(e => e.Name): </b>
    </div>
    <div class="col-md-10">
        @Html.DisplayFor(e => e.Name)
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <b>@Html.DisplayNameFor(e => e.BoxOfficeReturn):  </b>
    </div>
    <div class="col-md-10">
        @Html.DisplayFor(e => e.BoxOfficeReturn)
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <b>@Html.DisplayNameFor(e => e.ProductionYear):  </b>
    </div>
    <div class="col-md-10">
        @Html.DisplayFor(e => e.ProductionYear)
    </div>
</div>*@
@Html.Partial("_Details", Model)
<br />

@using (Html.BeginForm("Delete", "Movies", FormMethod.Post))
{
    @Html.HiddenFor(e => e.Id)

    <button type="submit" class="btn btn-success">Yes</button>
    @:&nbsp;
    @Html.ActionLink("No", "Index", null, htmlAttributes: new { @class = "btn btn-danger" })

}



@*Eski hali*@
@*@using (Html.BeginForm("Delete", "Movies", FormMethod.Post))
    {*@


@*@Html.DisplayForModel()*@

@*@Html.HiddenFor(e => e.Id)
    <div class="form-group">
        <b>@Html.DisplayNameFor(e => e.Name): </b>
        @Html.DisplayFor(e => e.Name)
    </div>
    <div class="form-group">
        <b>@Html.LabelFor(e => e.BoxOfficeReturn):  </b>
        @Html.DisplayFor(e => e.BoxOfficeReturn)
    </div>
    <div class="form-group">
        <b>@Html.DisplayNameFor(e => e.ProductionYear):  </b>
        @Html.DisplayFor(e => e.ProductionYear)
    </div>

    <button type="submit" class="btn btn-success">Yes</button>
    @:&nbsp;
    @Html.ActionLink("No", "Index", null, htmlAttributes: new { @class = "btn btn-danger" })*@

@*}*@

036_MoviesMvcWissen/Views/Movies/Edit.cshtml
@model Movie

@using _036_MoviesMvcWissen.Helpers

@{
    ViewBag.Title = "Edit Movie";
    var years = ViewBag.Years as SelectList; /*Checkkk*/
    var directors = (MultiSelectList)ViewBag.directors;
}

<h2>@ViewBag.Title</h2>

@*@Html.BeginForm("Edit", "Movies", FormMethod.Post)
    {

    }
    @{
        Html.EndForm();
    }*@

@using (Html.BeginForm("Edit", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Hidden("Id", Model.Id)
    @*<input type="hidden" name="Id" value="@Model.Id" />*@
    <div class="form-group">
        @Html.Label("tbName", "Name:  ")&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;
        @Html.TextBox("Name", Model.Name, new { @class = "form-control-sm", placeholder = "Enter movie name", id = "tbName" })
    </div>
    <div class="form-group">
        @Html.Label("ddlProductionYear", "Production Year:")&emsp;
        @Html.DropDownList("ProductionYear", years, new { @class = "form-control-sm", id = "ddlProductionYear" })
    </div>
    <div class="form-group">
        @Html.Label("tbBoxOfficeReturn", "Box Office Return:")&nbsp;
        @Html.TextBox("BoxOfficeReturn", Model.BoxOfficeReturn, new { @class = "form-control-sm",
       placeholder = "Enter movie box office return", id = "tbBoxOfficeReturn" })
    </div>
    @*<div class="form-group"> ilk yol
            <label for="ddlDirectos">Directors</label>
            <select id="ddlDirectos" class="form-control" name="Directors" multiple>
                @foreach (var director in directors)
                {
                    <option value="@director.Value">@director.Text</option>
                }
            </select>
        </div>*@
    <div class="form-group">
        @Html.Label("ddlDirectors", "Directors")
        @Html.ListBox("directorIds", directors, new { @class = "form-control", id = "ddlDirectors" })
    </div>

    <div class="form-group">
        @Html.Label("fuImage", "Image:")
        <br />
        <input type="file" name="Image" accept="image/*" id="fuImage" />
    </div>


    @*<input type="submit" class="btn btn-success" value="Save" />*@
    @Html.SaveButton()
    @:&nbsp;

    @*<input type="reset" class="btn btn-warning" value="Clear" />*@

    @Html.Button("Clear", "btn btn-warning", "reset")


}

036_MoviesMvcWissen/Views/Movies/Index.cshtml
@* 1 *@
@*@model List<_036_MoviesMvcWissen.Entities.Movie>*@
@* 2 *@
@model _036_MoviesMvcWissen.Models.ViewModels.MoviesIndexViewModel

@* 2 *@
@using _036_MoviesMvcWissen.Helpers

@{
    ViewBag.Title = "Movies";
}

@*@Html.Action("Welcome")*@
@{
    Html.RenderAction("Welcome");
}

<h2>@ViewBag.Title</h2>

@Html.ActionLink("Movie Report", "Movies", "Reports") @*("","action ismi",Controller)*@
<br />
<br />


@* 2 *@
@using (Html.BeginForm("Index", "Movies", FormMethod.Get))
{
    <table style="width: 100%;">
        <tr>
            <td style="width: 20%;">
                Production Year:
            </td>
            <td>
                @*@Html.DropDownList("YearId", Model.Years, new { @class = "form-control" })*@
                @Html.DropDownList("YearId", Model.Years, "-- All --", new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.Button("Search", "btn btn-primary", "submit")
            </td>
        </tr>
    </table>
}
<hr />

<a href="~/Movies/Add">Add Movie</a>
<br />

<label class="text-success">@TempData["Info"]</label>
<br />

@* 1 *@
@*<span>@Model.Count records found.</span>*@
@*<span>@ViewData["count"] records found.</span>*@
<span>@ViewBag.count records found.</span>

<table class="table">
    <tr>
        <td></td>
        <td></td>
        <td>
            <b>Name</b>
        </td>
        <td>
            <b>Production Year</b>
        </td>
        <td>
            <b>Box Office Return</b>
        </td>
    </tr>
    @* 1 *@
    @*@foreach (var movie in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(" ", "Details", new { id = movie.Id }, new { @class = "fa fa-info text-warning" })
                &nbsp;
                @Html.ActionLink(" ", "Edit", new { id = movie.Id }, new { @class = "fa fa-pencil-square-o text-success" })
                &nbsp;
                @Html.ActionLink(" ", "Delete", new { id = movie.Id }, new { @class = "fa fa-trash text-danger" })
            </td>
            <td>
                @movie.Name
            </td>
            <td>
                @movie.ProductionYear
            </td>
            <td>
                @movie.BoxOfficeReturn
            </td>
        </tr>
    }*@
    @* 2 *@
    @foreach (var movie in Model.Movies)
    {
        <tr>
            <td>
                @Html.ActionLink(" ", "Details", new { id = movie.Id }, new { @class = "fa fa-info text-warning" })
                &nbsp;
                @Html.ActionLink(" ", "Edit", new { id = movie.Id }, new { @class = "fa fa-pencil-square-o text-success" })
                &nbsp;
                @Html.ActionLink(" ", "Delete", new { id = movie.Id }, new { @class = "fa fa-trash text-danger" })
            </td>
            <td>
                @{
                    if (movie.FilePath != null)
                    {

                        <img src="../../@movie.FilePath" width="200" height="200" />
                        @*<img src="../../@movie.FilePath" class="img-thumbnail" style="width: 50% !important;"/>*@

                        @*<br /> fotoğrafı kaldırmak için
                @Html.ActionLink(" ", "Delete", new { id = movie.Id }, new { @class = "fa fa-ban text-danger mx-auto" })*@


                    }
                }

            </td>
            <td>
                @movie.Name
            </td>
            <td>
                @movie.ProductionYear
            </td>
            <td>
                @movie.BoxOfficeReturn
            </td>
        </tr>
    }
</table>

036_MoviesMvcWissen/Views/Movies/List.cshtml
@model  _036_MoviesMvcWissen.Models.ViewModels.MoviesIndexViewModel
@using _036_MoviesMvcWissen.Helpers

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-2">
            @Html.Label("lbName", "Name:")
        </div>
        <div class="col-md-10">
            @Html.TextBox("Name", "", new { @class = "form-control", id = "lbName" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-2">
            @Html.Label("lbPYear", "Production Year:")
        </div>
        <div class="col-md-10">
            @Html.DropDownList("YearId", Model.Years, "---All---", new { @class = "form-control", id = "lbPYear" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-2">
            @Html.Label("lbBoxOfficeReturn", "Box Office Return:")
        </div>
        @*<div class="col-md-1">Between</div>*@
        Between
        <div class="col-md-4">
            @Html.TextBox("Min", "", new { @class = "form-control", id = "lbBoxOfficeReturn", placeholder = "min" })
        </div>
        @*<div class="col-md-1">And</div>*@
        And
        <div class="col-md-4">
            @Html.TextBox("Max", "", new { @class = "form-control", placeholder = "max" })
        </div>
    </div>
    <br />


    <div class="row">
        <div class="col-md-1">
            @Html.Button("Search", "btn btn-primary", "Submit")
        </div>
        <div class="col-md-3">
            @Html.ActionLink("Clear","List","Movies", new { @class = "btn btn-secondary" })
            <a class="btn btn-secondary" href="@Url.RouteUrl("Default", new { controller = "Movies", action = "List"})">Clear</a>
        </div>
    </div>
    <br />
}



<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Production Year
        </th>
        <th>
            Box Office Return
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model.Movies)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductionYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BoxOfficeReturn)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
            </td>
        </tr>
    }

</table>