036_MoviesMvcWissen/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _036_MoviesMvcWissen.Contexts;
using _036_MoviesMvcWissen.Entities;
using _036_MoviesMvcWissen.Models.ViewModels;
using _036_MoviesMvcWissen.Validations.FluentValidation;
using FluentValidation.Results;

namespace _036_MoviesMvcWissen.Controllers
{
    public class DirectorsController : Controller
    {
        private MoviesContext db = new MoviesContext();

        // GET: Directors
        public ActionResult Index()
        {
            //return View(db.Directors.ToList());
            var model = new DirectorsIndexViewModel()
            {
                Directors = db.Directors.ToList()
            };
            return View(model);
        }

        // GET: Directors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Director director = db.Directors.Find(id);
            if (director == null)
            {
                return HttpNotFound();
            }
            return View(director);
        }

        // GET: Directors/Create
        public ActionResult Create()
        {
            var movies = db.Movies.Select(e => new SelectListItem()
            {
                Value = e.Id.ToString(),
                Text = e.Name
            }).ToList();
            ViewBag.Movies = new MultiSelectList(movies, "Value", "Text");
            return View();
        }

        // POST: Directors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Name,Surname,Retired")] Director director)
        [ActionName("Create")]
        //public ActionResult CreateNew() // 1
        public ActionResult CreateNew(FormCollection formCollection) // 2
        {
            var director = new Director()
            {
                Id = 0,
                //Name = Request.Form["Name"], // 1
                //Surname = Request.Form["Surname"] // 1
                Name = formCollection["Name"], // 2
                Surname = formCollection["Surname"] // 2
            };
            //var retired = Request.Form["Retired"]; // 1
            var retired = formCollection["Retired"]; // 2
            var movieIds = formCollection["movieIds"].Split(',');
            director.Retired = true;
            if (retired.Equals("false"))
                director.Retired = false;
            if (String.IsNullOrWhiteSpace(director.Name))
                ModelState.AddModelError("Name", "Director Name is required!");
            if (String.IsNullOrWhiteSpace(director.Surname))
                ModelState.AddModelError("Surname", "Director Surname is required!");
            if (director.Name.Length > 100)
                ModelState.AddModelError("Name", "Director Name must be maximum 100 characters!");
            if (director.Surname.Length > 100)
                ModelState.AddModelError("Surname", "Director Surname must be maximum 100 characters!");
            if (ModelState.IsValid)
            {
                director.MovieDirectors = movieIds.Select(e => new MovieDirector()
                {
                    MovieId = Convert.ToInt32(e),
                    DirectorId = director.Id
                }).ToList();
                db.Directors.Add(director);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Movies = new SelectList(db.Movies.Select(e => new SelectListItem() // select list
            {
                Value = e.Id.ToString(),
                Text = e.Name
            }).ToList(),"Value","Text");
            return View(director);
        }

        // GET: Directors/Edit/5
        #region Edit Get 1 eski hlai
        //public ActionResult Edit(int? id) // 1
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Director director = db.Directors.Find(id);
        //    if (director == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    var movies = db.Movies.Select(e => new SelectListItem()
        //    {
        //        Value = e.Id.ToString(),
        //        Text = e.Name
        //    }).ToList();
        //    var movieIds = director.MovieDirectors.Select(e => e.MovieId).ToList();
        //    ViewBag.Movies = new MultiSelectList(movies, "Value", "Text", movieIds);
        //    return View(director);
        //}
        #endregion
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var movies = db.Movies.Select(e => new SelectListItem()
            {
                Value = e.Id.ToString(),
                Text = e.Name
            }).ToList();

            var director = db.Directors.Find(id.Value);
            //List<int> _movieIds = db.MovieDirectors.Where(e => e.DirectorId == id.Value).Select(e => e.MovieId).ToList();// 1. yol
            List<int> _movieIds = director.MovieDirectors.Select(e => e.MovieId).ToList();// ALOO SORRR
            DirectorEditViewModel model = new DirectorEditViewModel();
            model.Director = director;
            model.movieIds = _movieIds;
            model.Movies = new MultiSelectList(movies, "Value", "Text", model.movieIds);//

            return View("EditNew",model);
        }

        // POST: Directors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region Edit POst 1 eski hali
        //public ActionResult Edit([Bind(Include = "Id,Name,Surname,Retired")] Director director, List<int> movieIds) //1
        //{
        //    var dbDirector = db.Directors.Find(director.Id);
        //    dbDirector.Name = director.Name;
        //    dbDirector.Surname = director.Surname;
        //    dbDirector.Retired = director.Retired;
        //    var dbMovieDirectors = db.MovieDirectors.Where(e => e.DirectorId == director.Id).ToList();
        //    foreach (var dbMovieDirector in dbMovieDirectors)
        //    {
        //        db.MovieDirectors.Remove(dbMovieDirector);
        //    }
        //    dbDirector.MovieDirectors = movieIds.Select(e => new MovieDirector()
        //    {
        //        MovieId = e,
        //        DirectorId = director.Id
        //    }).ToList();
        //    //if (ModelState.IsValid)
        //    //{
        //    //    db.Entry(director).State = EntityState.Modified;
        //    //    db.SaveChanges();
        //    //    return RedirectToAction("Index");
        //    //}
        //    DirectorValidator validator = new DirectorValidator();
        //    ValidationResult result = validator.Validate(director);
        //    if (result.IsValid)
        //    {
        //        db.Entry(dbDirector).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(director);
        //}
        #endregion
        public ActionResult Edit(DirectorEditViewModel directorEditViewModel)//*****
        {
            if (ModelState.IsValid)
            {
                var director = db.Directors.Find(directorEditViewModel.Director.Id);
                director.Name = directorEditViewModel.Director.Name;
                director.Surname = directorEditViewModel.Director.Surname;
                director.Retired = directorEditViewModel.Director.Retired;
                var movieDirectors = db.MovieDirectors.Where(e => e.DirectorId == director.Id).ToList();
                foreach (var movieDirector in movieDirectors)
                {
                    db.MovieDirectors.Remove(movieDirector);
                }
                director.MovieDirectors = directorEditViewModel.movieIds.Select(e => new MovieDirector()
                {
                    DirectorId = director.Id,
                    MovieId = e
                }).ToList();
                db.Entry(director).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(directorEditViewModel);
        }

        // GET: Directors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Director director = db.Directors.Find(id);
            if (director == null)
            {
                return HttpNotFound();
            }
            return View(director);
        }

        // POST: Directors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Director director = db.Directors.Find(id);
            db.Directors.Remove(director);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

036_MoviesMvcWissen/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _036_MoviesMvcWissen.Contexts;
using _036_MoviesMvcWissen.Entities;

namespace _036_MoviesMvcWissen.Controllers
{
    [Authorize]
    public class ReviewsController : Controller
    {
        private MoviesContext db = new MoviesContext();

        // GET: Reviews
        [AllowAnonymous]
        public ActionResult Index()
        {
            var reviews = db.Reviews.Include(r => r.Movie);
            return View(reviews.ToList());
        }

        // GET: Reviews/Details/5
        [Route("Reviews/Details/{no?}")]
        [AllowAnonymous]
        public ActionResult Details(int? no)
        {
            if (no == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(no);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // GET: Reviews/Create
        [Route("CreateReview")] // bu sayede createreview route'ı, default route'ın altında tanımlandığında da çalışmasını sağlıyoruz(bu olmazsa üstünde tanımlama yapmamız lazım)
        public ActionResult Create()
        {
            ViewBag.MovieId = new SelectList(db.Movies, "Id", "Name");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Content,Rating,Reviewer,MovieId")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Reviews.Add(review);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MovieId = new SelectList(db.Movies, "Id", "Name", review.MovieId);
            return View(review);
        }

        // GET: Reviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            ViewBag.MovieId = new SelectList(db.Movies, "Id", "Name", review.MovieId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content,Rating,Reviewer,MovieId")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Entry(review).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MovieId = new SelectList(db.Movies, "Id", "Name", review.MovieId);
            return View(review);
        }

        // GET: Reviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Reviews.Find(id);
            db.Reviews.Remove(review);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

036_MoviesMvcWissen/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Movie MVC @ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Plugins/bootstrap-datepicker-master/css/bootstrap-datepicker3.min.css" rel="stylesheet" />

    @RenderSection("myh2style", false)


    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Plugins/bootstrap-datepicker-master/js/bootstrap-datepicker.js"></script>

</head>
<body>
    <div class="container">
        <div class="header">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

                @*<a class="navbar-brand" href="~/Home/Index">Movies MVC</a>*@
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">Movies MVC</a>

                @if (User.Identity.IsAuthenticated)
                {
                    <span style="color:yellow;">Welcome @User.Identity.Name</span>
                    @:&nbsp;&nbsp;
                    <a style="color:yellow;" href="@Url.RouteUrl("Default", new { controller = "Login", action = "Logout" })">Logout</a>

                }
                else
                {
                    <a style="color:yellow;" href="@Url.RouteUrl("Default", new { controller = "Login", action = "Index" })">Login</a>

                }

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            @*Check*@
                            @*<a class="nav-link" href="~/Movies/Index">Movies <span class="sr-only">(current)</span></a>*@
                            <a class="nav-link" href="@Url.RouteUrl("Default", new { controller ="Movies", action ="Index" })">Movies Index</a>
                            @*<a class="nav-link" href="@Url.RouteUrl("Default", new { controller ="Movies", action ="List" })">List(Hüso)</a>*@
                        </li>
                        <li class="nav-item">
                            @*<a class="nav-link" href="@Url.Action("Index", "Directors")">Directors</a>*@
                            <a class="nav-link" href="@Url.RouteUrl("Default", new { controller ="Movies", action ="List" })">Movie List</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="@Url.Action("Index", "Directors")">Directors</a>
                        </li>
                        <li class="nav-item ">
                            @*<a class="nav-link" href="@Url.Action("Index", "Reviews")">Reviews</a>*@
                            <a class="nav-link" href="@Url.RouteUrl("GetReviews")">Reviews</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" href="@Url.Action("Index", "Home", new { area = "Admin" })">Admin</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Demos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="~/Demos/Razor1">Razor</a>
                                <a class="dropdown-item" href="~/Demos/FromRoute/8">Get Value From Route</a>
                                <a class="dropdown-item" href="~/Demos/FromQueryString?name=Çağıl&surname=Alsaç">Get Value From QueryString</a>
                                <a class="dropdown-item" href="~/Demos/GetPeople">Get People</a>
                                <a class="dropdown-item" href="~/Demos/GetPeopleAjax">Get People AJAX</a>
                                <a class="dropdown-item" href="~/Demos/GetPeopleHtml">Get People Html with Json </a>
                                <a class="dropdown-item" href="~/Demos/DivideByZero">HandleError - DivideByZero</a>
                                <a class="dropdown-item" href="~/addtwonumbers/7/8">Route Attribute - Add 2 Numbers</a>
                                <a class="dropdown-item" href="~/LogDemo/Index">Logging with IoC Container</a>
                            </div>
                        </li>

                    </ul>

                </div>
            </nav>
        </div>
        <div class="body">
            @RenderBody()
        </div>
        <div class="footer">

        </div>
    </div>


    @*<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>*@ @*öbür tarafa taşıdık (GetPeopleAjax)*@

    @RenderSection("ajaxScript", false) @* Ajax için*@


</body>
</html>

036_MoviesMvcWissen/Views/Shared/_Welcome.cshtml
@model string

<h4>@Model</h4>